import express from 'express';
import User from '../models/User.js';
import Room from '../models/Room.js';
import { v4 as uuidv4 } from 'uuid';

const router = express.Router();

// Login API
router.post('/login', async (req, res) => {
  try {
    const { username, password } = req.body;
    let user = await User.findOne({ username });
    
    if (!user) {
      user = new User({ username, password });
      await user.save();
    } else if (user.password !== password) {
      return res.status(401).json({ message: 'Invalid credentials' });
    }
    
    res.json({ message: 'Login successful', user: { username } });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
});

// Create Room API
router.post('/create-room', async (req, res) => {
  try {
    const { username } = req.body;
    // Generate short room ID for easy sharing
    const roomId = uuidv4().substring(0, 8);

    const room = new Room({
      roomId,
      createdBy: username,
      users: [username]
    });
    
    await room.save();
    // Only return roomId - socketId is auto-generated by Socket.io on connection
    res.json({ roomId });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
});

// Join Room API
router.post('/join-room', async (req, res) => {
  try {
    const { roomId, username } = req.body;
    const room = await Room.findOne({ roomId });

    if (!room) {
      return res.status(404).json({ message: 'Room not found' });
    }

    if (!room.users.includes(username)) {
      room.users.push(username);
      await room.save();
    }
    
    // Just confirm room exists - socketId is auto-generated by Socket.io
    res.json({ message: 'Joined successfully', roomId });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
});

export default router;